project:
  type: book

book:
  title: "Análise de dados com R"
  author: "Vitor Hugo Miro"
  date: "09/02/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Programação básica em R"
      chapters:
        - basics1.qmd
        - basics2.qmd
        - basics3.qmd
        - basics4.qmd
    - summary.qmd
    - references.qmd
  search:
    location: sidebar
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

