project:
  type: book

book:
  title: "Análise de dados com R"
  author: "Vitor Hugo Miro"
  date: "09/02/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - basics1.qmd
    - basics2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

